import * as THREE from 'https://esm.sh/three@0.160.0';
import { GLTFLoader } from 'https://esm.sh/three@0.160.0/examples/jsm/loaders/GLTFLoader.js';
import { RoundedBoxGeometry } from 'https://esm.sh/three@0.160.0/examples/jsm/geometries/RoundedBoxGeometry.js';
import { MeshoptDecoder } from 'https://cdn.jsdelivr.net/npm/three@0.160.0/examples/jsm/libs/meshopt_decoder.module.js';
const canvas=document.querySelector('#scene'),kind=document.body.dataset.scene;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()||'#07100d',.035);
const camera=new THREE.PerspectiveCamera(38,1,.1,100);camera.position.set(9,7,12);camera.lookAt(0,0,0);
const renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=kind==='agent'?.88:1.25;
scene.add(new THREE.HemisphereLight(0xeaffdd,0x07100d,kind==='agent'?1.55:2.4));const sun=new THREE.DirectionalLight(0xffffff,kind==='agent'?1.9:3);sun.position.set(-4,9,7);scene.add(sun);const world=new THREE.Group();scene.add(world);
const mat=(c,o=1)=>new THREE.MeshStandardMaterial({color:c,roughness:.65,metalness:.12,transparent:o<1,opacity:o});const line=(pts,c)=>{const g=new THREE.BufferGeometry().setFromPoints(pts);world.add(new THREE.Line(g,new THREE.LineBasicMaterial({color:c,transparent:true,opacity:.8})));};
const loading=document.createElement('div');loading.textContent='LOADING SCENE / PBR';Object.assign(loading.style,{position:'absolute',zIndex:3,right:'5vw',top:'112px',color:'var(--accent)',fontSize:'9px',fontWeight:900,letterSpacing:'.08em',transition:'opacity .5s ease'});canvas.after(loading);
const driveState={forward:false,back:false,left:false,right:false};
if(kind==='sound'){const controls=document.createElement('div');controls.className='scene-controls';controls.setAttribute('role','group');controls.setAttribute('aria-label','3D 场景视角');controls.innerHTML='<button type="button" data-view="overview" aria-pressed="true">全景</button><button type="button" data-view="vision" aria-pressed="false">视觉</button><button type="button" data-view="audio" aria-pressed="false">声场</button><button type="button" data-view="interface" aria-pressed="false">界面</button>';canvas.after(controls);const hint=document.createElement('div');hint.className='scene-hint';controls.after(hint)}
if(kind==='agent'){const controls=document.createElement('div');controls.className='scene-controls';controls.setAttribute('role','group');controls.setAttribute('aria-label','Embodied agent camera viewpoints');controls.innerHTML='<button type="button" data-view="overview" aria-pressed="false">OVERVIEW</button><button type="button" data-view="robot" aria-pressed="true">ROBOT POV</button><button type="button" data-view="target" aria-pressed="false">TARGET VIEW</button>';canvas.after(controls);const hint=document.createElement('div');hint.className='scene-hint';hint.textContent='SELECT CAMERA / 第一人称可随时切回全景';controls.after(hint);const drive=document.createElement('div');drive.className='robot-drive';drive.setAttribute('aria-label','Robot movement controls');drive.innerHTML='<button data-move="forward" aria-label="向前移动">↑</button><button data-move="left" aria-label="向左移动">←</button><button data-move="back" aria-label="向后移动">↓</button><button data-move="right" aria-label="向右移动">→</button><span>WASD / ARROWS</span>';hint.after(drive);drive.querySelectorAll('button').forEach(button=>{const key=button.dataset.move;button.addEventListener('pointerdown',e=>{e.preventDefault();driveState[key]=true;button.setPointerCapture(e.pointerId)});['pointerup','pointercancel','lostpointercapture'].forEach(type=>button.addEventListener(type,()=>driveState[key]=false))});const keyMap={KeyW:'forward',ArrowUp:'forward',KeyS:'back',ArrowDown:'back',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right'};addEventListener('keydown',e=>{if(keyMap[e.code]){driveState[keyMap[e.code]]=true;e.preventDefault()}});addEventListener('keyup',e=>{if(keyMap[e.code])driveState[keyMap[e.code]]=false})}
if(kind==='sound'){
 for(let i=0;i<7;i++){const wave=new THREE.Mesh(new THREE.TorusGeometry(1.1+i*.3,.014,6,100,Math.PI*1.45),new THREE.MeshBasicMaterial({color:i%2?0xffcf6d:0x8fffe2,transparent:true,opacity:.42-i*.04}));wave.position.set(2.35,.15,.2);wave.rotation.set(Math.PI/2,.12+i*.08,.45);world.add(wave)}
 [[-.5,1.4,.6],[4.1,1.55,.4],[.1,-.45,1.25]].forEach((p,i)=>{const orb=new THREE.Mesh(new THREE.IcosahedronGeometry(.08,2),new THREE.MeshBasicMaterial({color:i===2?0xffcf6d:0x8fffe2}));orb.position.set(...p);world.add(orb);line([new THREE.Vector3(...p),new THREE.Vector3(2.2,.1,0)],i===2?0xffcf6d:0x8fffe2)});
 const addPanel=(url,pos,rot)=>{const group=new THREE.Group(),frame=new THREE.Mesh(new RoundedBoxGeometry(1.08,1.72,.075,4,.055),new THREE.MeshStandardMaterial({color:0x09231f,metalness:.68,roughness:.2}));group.add(frame);const material=new THREE.MeshBasicMaterial({color:0xffffff});const face=new THREE.Mesh(new THREE.PlaneGeometry(.98,1.58),material);face.position.z=.041;group.add(face);new THREE.TextureLoader().load(url,t=>{t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=renderer.capabilities.getMaxAnisotropy();material.map=t;material.needsUpdate=true});group.position.set(...pos);group.rotation.set(...rot);world.add(group)};
 [['final_pdf/imdt_assets/vision-object.jpg',[-1,1.25,.55],[0,.42,-.025]],['final_pdf/imdt_assets/vision-location.jpg',[-.72,-.62,.72],[0,.36,.025]],['final_pdf/imdt_assets/vision-life-assistant.jpg',[5.1,1.25,.25],[0,-.48,.025]],['final_pdf/imdt_assets/vision-album.jpg',[4.82,-.62,.48],[0,-.42,-.025]]].forEach(args=>addPanel(...args));
}else if(kind==='agent'){
}else{
}
if(kind==='sound'){const controls=document.querySelector('.scene-controls'),hint=document.querySelector('.scene-hint');if(controls)controls.style.bottom=innerWidth<=800?'260px':'118px';if(hint)hint.remove()}
if(kind==='agent'){const controls=document.querySelector('.scene-controls');if(controls)controls.style.bottom=innerWidth<=800?'178px':'118px'}
const modelFiles={sound:'assets/hunyuan-portfolio/visionvoice/model-web.glb',agent:'assets/scene-redesign/embodied-agent-meshy-v3.glb',hunyuan:'assets/scene-redesign/hunyuan-vln-meshy.glb'};
const generated=new THREE.Group();world.add(generated);const loader=new GLTFLoader();loader.setMeshoptDecoder(MeshoptDecoder);const mount=(path,target,position,rotation=-.35)=>loader.load(path,gltf=>{const model=gltf.scene,box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),scale=target/Math.max(size.x,size.y,size.z);model.position.sub(center);model.scale.setScalar(scale);model.position.set(...position);model.rotation.y=rotation;model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.frustumCulled=true}});generated.add(model);loading.style.opacity='0'},xhr=>{if(xhr.total)loading.textContent=`LOADING SCENE / ${Math.round(xhr.loaded/xhr.total*100)}%`},()=>{loading.textContent='3D MODEL FALLBACK ACTIVE';setTimeout(()=>loading.style.opacity='0',1800)});if(kind==='sound'){mount('assets/visionvoice-3d/city-scene/model-web.glb',7,[2.2,-1.25,0],-.28);mount('assets/visionvoice-3d/life-terminal/model-web.glb',1.65,[-.15,1.35,.7],.42);mount('assets/visionvoice-3d/location-terminal/model-web.glb',1.55,[4.25,1.25,.35],-.65)}else mount(modelFiles[kind],kind==='agent'?7:7,[kind==='hunyuan'?2.35:3.35,kind==='agent'?-1.05:-.9,0],kind==='agent'?-0.28:-0.4);
const viewStates=kind==='agent'?{overview:{camera:[9,7,12],look:[1.8,.1,0],rotation:-.08,fov:38},robot:{camera:[4.25,-.1,4.15],look:[3.2,-.15,-1.2],rotation:0,fov:58},target:{camera:[5.8,1.65,3.7],look:[2.35,-.35,-.8],rotation:-.04,fov:46}}:{overview:{camera:[9,7,12],look:[1.2,.1,0],rotation:-.08,fov:38},vision:{camera:[5.5,3.2,7.2],look:[2.2,.55,1.55],rotation:-.18,fov:38},audio:{camera:[7.4,5.4,8.4],look:[2.15,.1,0],rotation:.34,fov:38},interface:{camera:[6.1,3.1,7],look:[2.05,.85,.25],rotation:-.52,fov:38}};let activeView=kind==='agent'?'robot':'overview',initialState=viewStates[activeView],cameraGoal=new THREE.Vector3(...initialState.camera),lookGoal=new THREE.Vector3(...initialState.look),lookNow=lookGoal.clone(),rotationGoal=initialState.rotation,fovGoal=initialState.fov;camera.position.copy(cameraGoal);camera.fov=fovGoal;camera.updateProjectionMatrix();document.querySelectorAll('.scene-controls button').forEach(button=>button.addEventListener('click',()=>{activeView=button.dataset.view;const state=viewStates[activeView];cameraGoal.set(...state.camera);lookGoal.set(...state.look);rotationGoal=state.rotation;fovGoal=state.fov;document.querySelectorAll('.scene-controls button').forEach(item=>item.setAttribute('aria-pressed',String(item===button)))}));
if(kind==='agent'){Object.assign(viewStates.robot,{camera:[5.55,-.92,2.35],look:[2.45,-.92,-1.55],fov:62});cameraGoal.set(...viewStates.robot.camera);lookGoal.set(...viewStates.robot.look);lookNow.copy(lookGoal);camera.position.copy(cameraGoal);camera.fov=viewStates.robot.fov;fovGoal=viewStates.robot.fov;camera.near=.85;camera.updateProjectionMatrix();document.querySelectorAll('.scene-controls button').forEach(button=>button.addEventListener('click',()=>{camera.near=button.dataset.view==='robot'?.85:.1;camera.updateProjectionMatrix()}))}
let px=0,py=0,visible=true;addEventListener('pointermove',e=>{px=(e.clientX/innerWidth-.5);py=(e.clientY/innerHeight-.5)});new IntersectionObserver(([e])=>visible=e.isIntersecting,{rootMargin:'150px'}).observe(canvas);
function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}resize();addEventListener('resize',resize,{passive:true});const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const moveForward=new THREE.Vector3(),moveRight=new THREE.Vector3(),moveDelta=new THREE.Vector3();function loop(t){if(visible){if(kind==='sound'||kind==='agent'){if(kind==='agent'&&activeView==='robot'&&Object.values(driveState).some(Boolean)){moveForward.subVectors(lookGoal,cameraGoal);moveForward.y=0;moveForward.normalize();moveRight.crossVectors(moveForward,new THREE.Vector3(0,1,0)).normalize();moveDelta.set(0,0,0);if(driveState.forward)moveDelta.add(moveForward);if(driveState.back)moveDelta.sub(moveForward);if(driveState.right)moveDelta.add(moveRight);if(driveState.left)moveDelta.sub(moveRight);if(moveDelta.lengthSq()){moveDelta.normalize().multiplyScalar(.045);cameraGoal.add(moveDelta);lookGoal.add(moveDelta)}}camera.position.lerp(cameraGoal,reduce?1:.045);lookNow.lerp(lookGoal,reduce?1:.06);camera.lookAt(lookNow);camera.fov+=(fovGoal-camera.fov)*(reduce?1:.06);camera.updateProjectionMatrix();world.rotation.y+=(rotationGoal+(kind==='sound'?px*.1:0)-world.rotation.y)*(reduce?1:.04);world.rotation.x+=((kind==='sound'?py*.035:0)-world.rotation.x)*(reduce?1:.04)}else if(!reduce){world.rotation.y=t*.00008+px*.18;world.rotation.x=py*.05}renderer.render(scene,camera)}requestAnimationFrame(loop)}requestAnimationFrame(loop);
